name: Scheduled Python Run

on:
  schedule:
    - cron: '10 5 * * *'

jobs:
  run_python_script:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' 

      - name: Install dependencies (if any)
        run: |
          pip install -r requirements.txt
          
      - name: Run Python script
        run: main.py
